### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by MFarelS** [MrHecka/heckayo-bot-telegram#1]
Naruh Token Nya Dimana Om?

**Comment by MrHecka** [comment]
Di environment gan terus dinamain TOKEN

**Comment by MFarelS** [comment]
![Screenshot_2021-01-24-16-55-43-318_com android chrome](https://user-images.githubusercontent.com/58540890/105626820-101d5e00-5e65-11eb-9ae3-e65e7dac5e3c.jpg)

Gini salah ya om?

**Comment by MFarelS** [comment]
Salah ya om?

**Comment by MrHecka** [comment]
Salah, yang bener gini....
![image](https://user-images.githubusercontent.com/71875420/105626942-17913700-5e66-11eb-9758-ea28c4ca45c4.png)

**Comment by MFarelS** [comment]
> Salah, yang bener gini....
> ![image](https://user-images.githubusercontent.com/71875420/105626942-17913700-5e66-11eb-9758-ea28c4ca45c4.png)

Wokeh, makasii Bang

**Comment by MrHecka** [comment]
> > Salah, yang bener gini....
> > ![image](https://user-images.githubusercontent.com/71875420/105626942-17913700-5e66-11eb-9758-ea28c4ca45c4.png)
> 
> Wokeh, makasii Bang

Tapi jangan lupa, semua file javascript yang ada 'process.env.TOKEN' nya kamu ganti sama token bot kamu satu satu kalau pake cara itu, kalau mau gampang yaaa tinggal buat env di launch.json kalau kamu pake vscode kayak gini, jadi gaperlu ganti satu satu..
![image](https://user-images.githubusercontent.com/71875420/105627014-9be3ba00-5e66-11eb-9e05-c06c0f988fb5.png)

**Comment by MFarelS** [comment]
> > > Salah, yang bener gini....
> > > ![image](https://user-images.githubusercontent.com/71875420/105626942-17913700-5e66-11eb-9758-ea28c4ca45c4.png)
> > 
> > 
> > Wokeh, makasii Bang
> 
> Tapi jangan lupa, semua file javascript yang ada 'process.env.TOKEN' nya kamu ganti sama token bot kamu satu satu kalau pake cara itu, kalau mau gampang yaaa tinggal buat env di launch.json kalau kamu pake vscode kayak gini, jadi gaperlu ganti satu satu..
> ![image](https://user-images.githubusercontent.com/71875420/105627014-9be3ba00-5e66-11eb-9e05-c06c0f988fb5.png)

Woke THX Om

**Comment by MFarelS** [comment]
> > > Salah, yang bener gini....
> > > ![image](https://user-images.githubusercontent.com/71875420/105626942-17913700-5e66-11eb-9758-ea28c4ca45c4.png)
> > 
> > 
> > Wokeh, makasii Bang
> 
> Tapi jangan lupa, semua file javascript yang ada 'process.env.TOKEN' nya kamu ganti sama token bot kamu satu satu kalau pake cara itu, kalau mau gampang yaaa tinggal buat env di launch.json kalau kamu pake vscode kayak gini, jadi gaperlu ganti satu satu..
> ![image](https://user-images.githubusercontent.com/71875420/105627014-9be3ba00-5e66-11eb-9e05-c06c0f988fb5.png)

Woke THX Om

**Comment by MrHecka** [comment]
Ok Ok sama sama ^_^
