### ISSUE TITLE
Bingung

### ISSUE THREAD

**Issue by MFarelS** [MrHecka/heckayo-bot-telegram#2]
Dapetin Ses Id Nya :3

**Comment by MrHecka** [comment]
sesi id instagram maksudnya ?

**Comment by MrHecka** [comment]
`1.) Pertama Ke www.instagram.com Dulu Terus Jangan Lupa Login`
`2.) Pergi Ke Development Tools (CTRL + SHIFT + I)`
`3.) Klik Tab Application (Kalau Pake Browser Firefox Namanya 'Storage')` 
`4.) Terus Buka Cookies Dan Cari Value 'sessionid'`

![image](https://user-images.githubusercontent.com/71875420/105634210-88007e00-5e8f-11eb-8f91-35987cba813b.png)

![image](https://user-images.githubusercontent.com/71875420/105634228-9e0e3e80-5e8f-11eb-89b9-5e268465bfb3.png)

**Comment by MFarelS** [comment]
Wokeh THX Bang, Saran : bikin tutor ambil apiknya, rada bingung saya wkwkwk

**Comment by MFarelS** [comment]
> Wokeh THX Bang, Saran : bikin tutor ambil apikeynya, rada bingung saya wkwkwk

**Comment by MrHecka** [comment]
> > Wokeh THX Bang, Saran : bikin tutor ambil apikeynya, rada bingung saya wkwkwk

di readme udah ku cantumin btw

**Comment by MFarelS** [comment]
> > > Wokeh THX Bang, Saran : bikin tutor ambil apikeynya, rada bingung saya wkwkwk
> 
> di readme udah ku cantumin btw

Hehe

**Comment by MrHecka** [comment]
> > > > Wokeh THX Bang, Saran : bikin tutor ambil apikeynya, rada bingung saya wkwkwk
> > 
> > 
> > di readme udah ku cantumin btw
> 
> Hehe

ini anda btw Author yang buat Bot Nulis itu ya :v

**Comment by MFarelS** [comment]
> > > > > Wokeh THX Bang, Saran : bikin tutor ambil apikeynya, rada bingung saya wkwkwk
> > > 
> > > 
> > > di readme udah ku cantumin btw
> > 
> > 
> > Hehe
> 
> ini anda btw Author yang buat Bot Nulis itu ya :v

Lah Awokwaokwaok

**Comment by MFarelS** [comment]
Bingung Dapetin ApiKey
>geniusapi
> apikeytmdb
> apitwt
Om:3

**Comment by MrHecka** [comment]
> Bingung Dapetin ApiKey
> 
> > geniusapi
> > apikeytmdb
> > apitwt
> > Om:3

**Kalau untuk geniusapi (api key genius lyrics),** 
1.) lomgin dulu :v di => https://genius.com
2.) lalu buka link ini => https://genius.com/api-clients
3.) terus klik new api client terus isi form nya
4.) nanti muncul api key nya itu kamu copy

**Untuk apikeytmdb (API The Movie Database),**
1.) Login dulu ke link => https://www.themoviedb.org
2.) terus kalau udah lomgin :v, pergi ke link => https://www.themoviedb.org/settings/api
3.) nanti muncul api key nya terus kamu copy

**Untuk apitwt (api key twitter),**
1.) Login dulu di twitter.com untuk akun api key nya
2.) Pergi ke link ini => https://developer.twitter.com/en/portal/dashboard
3.) Isi form nya, emang agak banyak ngisi form nya :v tapi isi aja ikutin sesuai yang diminta twitter nya
4.) Kalau application nya udah di acc sama twitter nya, nanti langsung pergi ke dashboard aja dari link no.2 tadi, terus klik gambar kunci (keys & token) nah nanti muncul dah tuh api key twitter nya.

apitwt = Api Key
apisecrettwt = Secret Api Key
tokentwt = Access token
secrettokentwt = Secret access token

**Comment by MrHecka** [comment]
> > > > > > Wokeh THX Bang, Saran : bikin tutor ambil apikeynya, rada bingung saya wkwkwk
> > > > 
> > > > 
> > > > di readme udah ku cantumin btw
> > > 
> > > 
> > > Hehe
> > 
> > 
> > ini anda btw Author yang buat Bot Nulis itu ya :v
> 
> Lah Awokwaokwaok

Saya izin ambil sc nya juga ya buat nulis3.js :v, lumayan buat belajar saya juga, makasih bang🙏

**Comment by MFarelS** [comment]
> > Bingung Dapetin ApiKey
> > > geniusapi
> > > apikeytmdb
> > > apitwt
> > > Om:3
> 
> **Kalau untuk geniusapi (api key genius lyrics),**
> 1.) lomgin dulu :v di => https://genius.com
> 2.) lalu buka link ini => https://genius.com/api-clients
> 3.) terus klik new api client terus isi form nya
> 4.) nanti muncul api key nya itu kamu copy
> 
> **Untuk apikeytmdb (API The Movie Database),**
> 1.) Login dulu ke link => https://www.themoviedb.org
> 2.) terus kalau udah lomgin :v, pergi ke link => https://www.themoviedb.org/settings/api
> 3.) nanti muncul api key nya terus kamu copy
> 
> **Untuk apitwt (api key twitter),**
> 1.) Login dulu di twitter.com untuk akun api key nya
> 2.) Pergi ke link ini => https://developer.twitter.com/en/portal/dashboard
> 3.) Isi form nya, emang agak banyak ngisi form nya :v tapi isi aja ikutin sesuai yang diminta twitter nya
> 4.) Kalau application nya udah di acc sama twitter nya, nanti langsung pergi ke dashboard aja dari link no.2 tadi, terus klik gambar kunci (keys & token) nah nanti muncul dah tuh api key twitter nya.
> 
> apitwt = Api Key
> apisecrettwt = Secret Api Key
> tokentwt = Access token
> secrettokentwt = Secret access token

Wokeh Makasii Om

**Comment by MFarelS** [comment]
> > > > > > > Wokeh THX Bang, Saran : bikin tutor ambil apikeynya, rada bingung saya wkwkwk
> > > > > 
> > > > > 
> > > > > di readme udah ku cantumin btw
> > > > 
> > > > 
> > > > Hehe
> > > 
> > > 
> > > ini anda btw Author yang buat Bot Nulis itu ya :v
> > 
> > 
> > Lah Awokwaokwaok
> 
> Saya izin ambil sc nya juga ya buat nulis3.js :v, lumayan buat belajar saya juga, makasih bang🙏

Panggil saya adek ada bang:3

**Comment by MrHecka** [comment]
> > > > > > > > Wokeh THX Bang, Saran : bikin tutor ambil apikeynya, rada bingung saya wkwkwk
> > > > > > 
> > > > > > 
> > > > > > di readme udah ku cantumin btw
> > > > > 
> > > > > 
> > > > > Hehe
> > > > 
> > > > 
> > > > ini anda btw Author yang buat Bot Nulis itu ya :v
> > > 
> > > 
> > > Lah Awokwaokwaok
> > 
> > 
> > Saya izin ambil sc nya juga ya buat nulis3.js :v, lumayan buat belajar saya juga, makasih bang🙏
> 
> Panggil saya adek ada bang:3

Wawkawoawkak panggil 'gan' aja dah biar enak :v

**Comment by MFarelS** [comment]
> > > > > > > > > Wokeh THX Bang, Saran : bikin tutor ambil apikeynya, rada bingung saya wkwkwk
> > > > > > > 
> > > > > > > 
> > > > > > > di readme udah ku cantumin btw
> > > > > > 
> > > > > > 
> > > > > > Hehe
> > > > > 
> > > > > 
> > > > > ini anda btw Author yang buat Bot Nulis itu ya :v
> > > > 
> > > > 
> > > > Lah Awokwaokwaok
> > > 
> > > 
> > > Saya izin ambil sc nya juga ya buat nulis3.js :v, lumayan buat belajar saya juga, makasih bang🙏
> > 
> > 
> > Panggil saya adek ada bang:3
> 
> Wawkawoawkak panggil 'gan' aja dah biar enak :v

Awokwaokwaok, boleh PullRequest Gan?

**Comment by MrHecka** [comment]
> > > > > > > > > > Wokeh THX Bang, Saran : bikin tutor ambil apikeynya, rada bingung saya wkwkwk
> > > > > > > > 
> > > > > > > > 
> > > > > > > > di readme udah ku cantumin btw
> > > > > > > 
> > > > > > > 
> > > > > > > Hehe
> > > > > > 
> > > > > > 
> > > > > > ini anda btw Author yang buat Bot Nulis itu ya :v
> > > > > 
> > > > > 
> > > > > Lah Awokwaokwaok
> > > > 
> > > > 
> > > > Saya izin ambil sc nya juga ya buat nulis3.js :v, lumayan buat belajar saya juga, makasih bang🙏
> > > 
> > > 
> > > Panggil saya adek ada bang:3
> > 
> > 
> > Wawkawoawkak panggil 'gan' aja dah biar enak :v
> 
> Awokwaokwaok, boleh PullRequest Gan?

Untuk apa kalo boleh tau?

**Comment by MFarelS** [comment]
> > > > > > > > > > > Wokeh THX Bang, Saran : bikin tutor ambil apikeynya, rada bingung saya wkwkwk
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > di readme udah ku cantumin btw
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Hehe
> > > > > > > 
> > > > > > > 
> > > > > > > ini anda btw Author yang buat Bot Nulis itu ya :v
> > > > > > 
> > > > > > 
> > > > > > Lah Awokwaokwaok
> > > > > 
> > > > > 
> > > > > Saya izin ambil sc nya juga ya buat nulis3.js :v, lumayan buat belajar saya juga, makasih bang🙏
> > > > 
> > > > 
> > > > Panggil saya adek ada bang:3
> > > 
> > > 
> > > Wawkawoawkak panggil 'gan' aja dah biar enak :v
> > 
> > 
> > Awokwaokwaok, boleh PullRequest Gan?
> 
> Untuk apa kalo boleh tau?

Fitur Harta Tahta Gan

**Comment by MrHecka** [comment]
> > > > > > > > > > > > Wokeh THX Bang, Saran : bikin tutor ambil apikeynya, rada bingung saya wkwkwk
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > di readme udah ku cantumin btw
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Hehe
> > > > > > > > 
> > > > > > > > 
> > > > > > > > ini anda btw Author yang buat Bot Nulis itu ya :v
> > > > > > > 
> > > > > > > 
> > > > > > > Lah Awokwaokwaok
> > > > > > 
> > > > > > 
> > > > > > Saya izin ambil sc nya juga ya buat nulis3.js :v, lumayan buat belajar saya juga, makasih bang🙏
> > > > > 
> > > > > 
> > > > > Panggil saya adek ada bang:3
> > > > 
> > > > 
> > > > Wawkawoawkak panggil 'gan' aja dah biar enak :v
> > > 
> > > 
> > > Awokwaokwaok, boleh PullRequest Gan?
> > 
> > 
> > Untuk apa kalo boleh tau?
> 
> Fitur Harta Tahta Gan

ok dah, sudah gan

**Comment by MFarelS** [comment]
Cek issue baru mhank
