### ISSUE TITLE
Bingung #2

### ISSUE THREAD

**Issue by MFarelS** [MrHecka/heckayo-bot-telegram#6]
![IMG_20210126_171100](https://user-images.githubusercontent.com/58540890/105831656-91a5f500-5ff9-11eb-9fb3-49b78eaabb5f.jpg)
ApiKey Genius Yang Mana Gan?

**Comment by MFarelS** [comment]
CLIENT ACCESS TOKEN??

**Comment by MrHecka** [comment]
> CLIENT ACCESS TOKEN??

Yang client secret coba

**Comment by MFarelS** [comment]
> > CLIENT ACCESS TOKEN??
> 
> Yang client secret coba

Wokeh, THX Om
