### ISSUE TITLE
Token dimana

### ISSUE THREAD

**Issue by dhyZx** [MrHecka/heckayo-bot-telegram#7]
Bang Naro token dimana?

**Comment by MFarelS** [comment]
Pm

**Comment by MrHecka** [comment]
> Bang Naro token dimana?

https://github.com/MrHecka/heckayo-bot-telegram/issues/2

**Comment by MrHecka** [comment]
> Bang Naro token dimana?

https://github.com/MrHecka/heckayo-bot-telegram/issues/1

**Comment by MFarelS** [comment]
Close

**Comment by MFarelS** [comment]
Close issue
