### ISSUE TITLE
pak mau nanya

### ISSUE THREAD

**Issue by HAFizh-15** [MrHecka/heckayo-bot-telegram#8]
isi token nya per file atau ada di 1 file?

**Comment by MrHecka** [comment]
> isi token nya per file atau ada di 1 file?

ngisi tokennya lewat environment gan, kalau pake visual studio code, 
bisa pake cara ini :
 
![image](https://user-images.githubusercontent.com/71875420/106228800-b3cc8c80-621e-11eb-897d-d0b331cf7ffa.png)
(isi di file launch.json)

**Comment by HAFizh-15** [comment]
owalah, makasih info nya pak

**Comment by HAFizh-15** [comment]
btw itu ada di file mana?

**Comment by MrHecka** [comment]
> btw itu ada di file mana?

Di launch.json kalo pake vscode, tergantung kamu jalanin js nya pake apa, kalo gamau pake environment ya ganti process.env.{nama_token}  nya ubah jadi token/api key sesuai namanya
